### ISSUE TITLE
Reminder feature

### ISSUE THREAD

**Issue by hmoffatt** [nebhead/garage-zero#10]
It would be cool if Garage-Zero could remind me that the door is open every X minutes, after the initial notification that it's open.

Then I could get a reminder after Y minutes, and a notification every X minutes after that.

What do you think?

**Comment by nebhead** [comment]
Definitely an option to add something like this.  In fact, I think it might be pretty simple.  Maybe call it Nag Mode.  :)  I can look into this as well when time permits this week (or weekend).  Thanks!

**Comment by hmoffatt** [comment]
Thanks. I'm happy to take a look, but I don't want to take over your project :-)

Now that I have notifications and email working well for me I need to tidy up my hardware and actually install it in my garage.

**Comment by nebhead** [comment]
Oh feel free!  I'm not likely to get to it this week, so if you want to jump on it before then, I'm totally cool with that. :)
