### ISSUE TITLE
Change to sensor input

### ISSUE THREAD

**Issue by hmoffatt** [nebhead/garage-zero#15]
This is more of a note for anyone else wanting to set up a Garage-Zero and might be better in a wiki article than an issue, so feel free to just close it!

I think the door sensor input is more complicated than it needs to be. This is the same for the hardware design you started with (http://www.driscocity.com/idiots-guide-to-a-raspberry-pi-garage-door-opener/), and the one HE started with (http://freemansgarage.com/blog/?p=587).

The design has a 10k pullup resistor and a 1k pull down. Firstly there is no need for the pull down, it is ok to have the switch ground the input. Secondly there are fixed pullup resistors of 1.8k on GPIOs 2 and 3 of the Raspberry PI. So you can just connect the switch directly to +3.3V and GPIO 2 without adding any extra resistors.

One of the commenters on the original article suggested this, and the author said it didn't work for him. It's working fine for me though.

**Comment by nebhead** [comment]
Well that's good news!  Frankly, I just blindly followed the original articles advice, as when I started this project I was pretty new to the whole thing.  But absolutely true I think that the pull-down is probably not necessary.  I can add a note to the readme as such.

**Comment by hmoffatt** [comment]
I was going to go find the resistors and solder something up, but then I got lazy and started studying the circuit instead!

The 1.8k pullup on GPIOs 2 and 3 is stronger than the 10k external so I can't think why the original designer would have had any problem with that.
