### ISSUE TITLE
Door Status only showing "green open"

### ISSUE THREAD

**Issue by AppleManDos** [nebhead/garage-zero#29]
Hi. Thank you for the great work and explanations.

I powered it up for the first time yesterday and the Door Status shows "green closed" regardless of whether the magnetic switch is connected or in proximity with its contact. I was using a long length of Cat5 wires to reach the door.

I tested my magnetic switch using a multi-meter and it works.

I powered it off and left it overnight.

Today, I hooked it up again to troubleshoot the magnetic switch.

I noticed the Door Status was working "red open" / "green closed" with the magnetic switch connected with a very short wire. When I reconnected the long wire, the status remains as "green closed" like it did yesterday. I cannot get it to show the "red open" state again. I have disconnected the magnetic switch, used short wires again, swapped polarity, restarted everything. Still showing "green closed" no matter what I do.

I have tried different power supplies (0.7 A to 2.3 A) also.

I would expect a disconnected magnetic switch to show "red open" but it only showed up once. What could be causing it to constantly show "green closed"?

I am using both the 1 kΩ and 10 kΩ resistors. Should I eliminate them and change to GPIO 2 or 3 and change control.py as mentioned in the note (Optional Design Change)?

**Comment by nebhead** [comment]
> I noticed the Door Status was working "red open" / "green closed" with the magnetic switch connected with a very short wire. When I reconnected the long wire, the status remains as "green closed" like it did yesterday. I cannot get it to show the "red open" state again. I have disconnected the magnetic switch, used short wires again, swapped polarity, restarted everything. Still showing "green closed" no matter what I do.
> 
> I have tried different power supplies (0.7 A to 2.3 A) also.
> 
> I would expect a disconnected magnetic switch to show "red open" but it only showed up once. What could be causing it to constantly show "green closed"?
 
> I am using both the 1 kΩ and 10 kΩ resistors. Should I eliminate them and change to GPIO 2 or 3 and change control.py as mentioned in the note (Optional Design Change)?

Hmm... this should all work just fine with the resistor setup that is documented, so further testing is needed.  If you have a multi-meter, can you check the voltage level at GPIO18 (Pin 12), while powered on and the magnetic switch is OPEN and when the magnetic switch is CLOSED.  

Also, just to make sure, are you using the same magnetic switch that is linked in the documentation?   (https://www.amazon.com/dp/B0009SUF08/ref=cm_sw_em_r_mt_dp_U_htppCbJ7B52KG)

**Comment by AppleManDos** [comment]
I took the resistors out and it worked but not for long. I think my daughterboard was giving me trouble so I removed it completely. Things are working properly now. I will test it for a while and report back.

I think the resistors were fine. It was probably just my wiring.

**Comment by nebhead** [comment]
Great to hear!  Hope it goes smoothly from here on out.  Enjoy!

**Comment by AppleManDos** [comment]
It has been running very well for several weeks now. I installed an infrared camera. The magnetic switch I used is a cheap one from [Aliexpress](https://www.aliexpress.com/item/1005003498078487.html).

For remote access, I am using Zerotier.

Everything working great.

**Comment by nebhead** [comment]
> Everything working great.

Awesome!  Glad it's working well for you, and thank you for checking back in and giving an update!  Enjoy and happy new year!
