### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by hmoffatt** [nebhead/garage-zero#3]
Python 2 is going to be end of life real soon. Can I suggest upgrading? The webapp part seems to run OK in Python 3, but the control part does not - the urllib2 and email libraries have changed.

**Comment by nebhead** [comment]
I love suggestions!  Keep them coming - I want to make this project better.  

I just discovered that Python 2 is going to be end of life'd soon myself and that got me thinking along the same lines.  Frankly, was a bit too lazy to do any investigation, but it's perhaps time to change that.  Do you happen to know if the pi foundation is going to make changes to their OS image to make Python 3 the default?   I suspect that will be the case.  Maybe for the time being, I can create a check for python 2 / 3 and run the appropriate code for either.  Again, give me time on this one and I'll get it updated.

**Comment by hmoffatt** [comment]
I don't think /usr/bin/python will be changing to python 3 too soon, but you can add ```#!/usr/bin/env python3``` to the top of control.py (and make it executable) to tell linux you want to run it with python3, and launch it just as ./control.py instead of "python control.py".

Python comes with a tool called 2to3 which does conversion for you. At a glance will be all you need to do there.

Also you would have to install gunicorn3 instead of gunicorn and update the supervisor/systemd files.

**Comment by ruddj** [comment]
I've modified my fork to use Python 3 but I am unsure of the best way to submit a pull, as it would introduce breaking changes to an existing install using Python2. Should I just submit as a separate branch or some other way? Any suggestions?

**Comment by nebhead** [comment]
A separate branch would be perfect.  Thanks!!

**Comment by nebhead** [comment]
FYI - I've updated this project, moving to Python 3 by default.  No more Python 2.x support. :)  With that, I'm closing this issue.
