### ISSUE TITLE
Email login

### ISSUE THREAD

**Issue by hmoffatt** [nebhead/garage-zero#5]
For many mail servers you will need a username different to your email address. Also some servers won't require a login at all so it should be possible to disable login by leaving the username/password blank.

**Comment by nebhead** [comment]
Ah, thanks for the heads up.  I kind of created this with only one e-mail server test environment so perhaps I need to update so that it's possible to leave the username/password blank.  Give me a few days to get this updated.

**Comment by hmoffatt** [comment]
Thanks for listening to all my issues! 

I also need to be able to turn off the starttls call. I have a local email relay which doesn't require any login or TLS.

I would be happy to work on this and submit a pull request, since my environment is a bit unusual.

**Comment by nebhead** [comment]
Yes, absolutely!  I approved your other pull request (thank you!) and merged it in.  Still at work (west coast California here), but later I'll push the fix for the other silly e-mail issue.

**Comment by hmoffatt** [comment]
Thanks, I'll submit a PR in a few days when I have had a chance to work on it.
