### ISSUE TITLE
Email doesn't work if only a single address specified

### ISSUE THREAD

**Issue by hmoffatt** [nebhead/garage-zero#6]
If you only have a single address then control.py tries to assign to toaddrlist[0], but toaddrlist doesn't exist. The following patch fixes it.

By the way, you can just split the original list on comma without checking for commas first - split return a single element list if no commas are found.

```
diff --git a/control.py b/control.py
index 8f63a89..d4a2e38 100644
--- a/control.py
+++ b/control.py
@@ -63,7 +63,7 @@ def SndEmail(settings, notifyevent):
                        # process string into list of e-mail addresses
                        toaddrlist = toaddr.split(",")
                else:
-                       toaddrlist[0] = toaddr
+                       toaddrlist = [toaddr]^M
 
                index = 0
                while(index < len(toaddrlist)):

```

**Comment by nebhead** [comment]
Oops!  Thanks for catching this one and thanks for providing the code update.  I'll get this fixed and uploaded as soon as I get home from work today.
